// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVhDrjR3TCqzZJeGb8ZccpD-0FRYv-eso',
    appId: '1:351014482526:web:3f374893f65388400d3acf',
    messagingSenderId: '351014482526',
    projectId: 'natashacollection-a74e3',
    authDomain: 'natashacollection-a74e3.firebaseapp.com',
    storageBucket: 'natashacollection-a74e3.appspot.com',
    measurementId: 'G-7PRC27NC4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqxflOPMirozfojnmbiasURU8RmqcNz84',
    appId: '1:351014482526:android:56b95d3698929f0d0d3acf',
    messagingSenderId: '351014482526',
    projectId: 'natashacollection-a74e3',
    storageBucket: 'natashacollection-a74e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdOsxmnvIKjj1p5zJnKD3TeWKDzq6q-Nc',
    appId: '1:351014482526:ios:a80ba48e8f09c03c0d3acf',
    messagingSenderId: '351014482526',
    projectId: 'natashacollection-a74e3',
    storageBucket: 'natashacollection-a74e3.appspot.com',
    iosBundleId: 'com.example.natashaCollection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdOsxmnvIKjj1p5zJnKD3TeWKDzq6q-Nc',
    appId: '1:351014482526:ios:a80ba48e8f09c03c0d3acf',
    messagingSenderId: '351014482526',
    projectId: 'natashacollection-a74e3',
    storageBucket: 'natashacollection-a74e3.appspot.com',
    iosBundleId: 'com.example.natashaCollection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVhDrjR3TCqzZJeGb8ZccpD-0FRYv-eso',
    appId: '1:351014482526:web:ad95906ff51c2f520d3acf',
    messagingSenderId: '351014482526',
    projectId: 'natashacollection-a74e3',
    authDomain: 'natashacollection-a74e3.firebaseapp.com',
    storageBucket: 'natashacollection-a74e3.appspot.com',
    measurementId: 'G-3VTFQKZBY6',
  );
}
